parser: '@typescript-eslint/parser'

plugins:
  - '@typescript-eslint'

parserOptions:
  ecmaVersion: 2019
  sourceType: 'module'
  project: './tsconfig.json'

env:
  browser: true
  es6: true

overrides:
  - files:
      - '*.spec.ts'
    env:
      es6: true
      jasmine: true
      jest: true
      node: true

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'

rules:
  no-restricted-imports:
    - error
    - patterns:
        - 'rxjs/Rx'
  '@typescript-eslint/prefer-readonly': error
  '@typescript-eslint/explicit-function-return-type':
    - off
  '@typescript-eslint/member-delimiter-style':
    - error
    - multiline:
        delimiter: none
  '@typescript-eslint/no-non-null-assertion':
    - off
  '@typescript-eslint/no-explicit-any':
    - off
  '@typescript-eslint/explicit-member-accessibility':
    - error
    - accessibility: no-public
  '@typescript-eslint/no-empty-function':
    - error
    - allow:
        - arrowFunctions
        - constructors
