version: '3'

services:
  backend: #name of the second service
    build: ./backend # specify the directory of the Dockerfile
    ports:
      - '3000:3000' #specify ports forewarding
    container_name: back-container
    restart: always
  frontend: #name of the first service
    build: ./frontend # specify the directory of the Dockerfile
    ports:
      - '4200:4200' # specify port forewarding
    container_name: front-container
    restart: always
