version: "3"

services:
  backend: #name of the second service
    build: ./backend # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding
    container_name: back-container
    restart: always
  frontend: #name of the first service
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /src/app/frontend/node_modules
    ports:
      - "4200:4200" # specify port forewarding
      - "49153:49153"
    container_name: front-container
    restart: always
